require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

$static_libraries = [
  'RNVectorIcons', 'RNPermissions', 'RNReanimated', 'RNScreens'
]

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if $static_libraries.include?(pod.name) || pod.name.start_with?('Permission-')
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

target 'AntsomirnsdkExample' do
  config_pod = use_native_modules!
  # use_frameworks!

  use_react_native!(:path => config_pod[:reactNativePath])

  pod 'antsomirnsdk', :path => '../..'
  # pod 'AntsomiFramework'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.93.0' })

  post_install do |installer|

    react_native_post_install(
      installer,
      config_pod[:reactNativePath],
      :mac_catalyst_enabled => false
    )
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
    end
  end
end

# target 'NotificationService' do
#  #use_frameworks!
#   pod 'AntsomiFramework'
# end